name: Trigger CICD Build Workflow

on:
  push

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CICD Build Workflow in cicd-environ.cicd
        run: |
          # Set the required variables
          repo_owner="jpbarto"
          repo_name="cicd-environ.cicd"
          event_type="trigger-cicd-build"
          repository="${{ github.repository }}"
          sha="${{ github.sha }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"repository\": \"$repository\", \"sha\": \"$sha\", \"unit\": false, \"integration\": true}}"
